### ISSUE TITLE
Value Error : font-style bold is not a font-style value 

### ISSUE THREAD

**Issue by Geekcoder555** [internetarchive/wayback-machine-chrome#103]
Description:

Value Error : font-style bold is not a font-style value 
file : sequences.css

Acceptance criteria:
Above file should be updated accordingly.

Time:
5-10 min

**Comment by sankalpdayal5** [comment]
Please close the issue as this has already been solved

**Comment by VishnuRaghavan** [comment]
Why isn't the issue closed?
