### ISSUE TITLE
Validation issues in Javascript file sequences.js

### ISSUE THREAD

**Issue by Geekcoder555** [internetarchive/wayback-machine-chrome#104]
Description:
Validation issues in Javascript file sequences.js.
Line Col
15 |   23 | Use '!==' to compare with ''
36 |  10 | Missing semicolon.
24 |  13 | 'base_url' is defined but never used.
14 |  64 | 'sendResponse' is defined but never used.
14 |  56 | 'sender' is defined but never used.
8 |    17 | 'chrome' is not defined.
13 |   1 | 'chrome' is not defined.
14 |   1 | 'chrome' is not defined.
41 |   11 | 'wb' is not defined.

Acceptance criteria:
The above file should be updated according to the issues mentioned above.

Time:
10-15 min

**Comment by akshat14714** [comment]
@AnkitKhatri55555 I would like to work on this issue. Can you please help me do that
