### ISSUE TITLE
Errors in JavaScript File jquery.js.

### ISSUE THREAD

**Issue by Geekcoder555** [internetarchive/wayback-machine-chrome#106]
Description:

Errors in JavaScript File jquery.js.

Following errors are obtained in file jquery.js

Line | Col | Errors jquery.js
-- | -- | --
133 | 18 | Use '===' to compare with 'null'.
225 | 43 | Use '!==' to compare with 'null'.
283 | 20 | Use '!==' to compare with 'null'.
334 | 18 | Use '===' to compare with 'null'.
379 | 21 | Use '===' to compare with 'null'.
388 | 18 | Use '!==' to compare with 'null'.
403 | 20 | Use '===' to compare with 'null'.
453 | 28 | Use '!==' to compare with 'null'.
463 | 28 | Use '!==' to compare with 'null'.
733 | 43 | Expected an assignment or function call and instead saw an expression.
1171 | 20 | ['ID'] is better written in dot notation.
1177 | 18 | ['ID'] is better written in dot notation.
1184 | 20 | ['ID'] is better written in dot notation.
1195 | 18 | ['ID'] is better written in dot notation.
1225 | 14 | ['TAG'] is better written in dot notation.
1257 | 14 | ['CLASS'] is better written in dot notation.
1721 | 27 | ['CHILD'] is better written in dot notation.
1771 | 29 | Use '===' to compare with 'null'.
2060 | 33 | Expected an assignment or function call and instead saw an expression.
2081 | 33 | ['empty'] is better written in dot notation.
2105 | 54 | Use '===' to compare with 'null'.
2155 | 13 | ['nth'] is better written in dot notation.
2155 | 35 | ['eq'] is better written in dot notation.
2339 | 22 | Use '!==' to compare with 'null'.
2517 | 55 | ['TAG'] is better written in dot notation.
2519 | 59 | Use '===' to compare with 'null'.
2529 | 52 | Use '!==' to compare with 'null'.
2672 | 34 | ['ID'] is better written in dot notation.
2685 | 22 | ['needsContext'] is better written in dot notation.
2776 | 40 | Use '===' to compare with 'null'.
2846 | 2 | Unnecessary semicolon.
2857 | 20 | Confusing use of '!'.
3151 | 35 | Use '===' to compare with 'null'.
3501 | 21 | Value of 'value' may be overwritten in IE 8 and earlier.
3735 | 32 | Use '!==' to compare with 'null'.
3960 | 20 | Use '===' to compare with 'null'.
4023 | 60 | Confusing use of '!'.
4664 | 30 | Use '!==' to compare with 'null'.
4924 | 15 | Use '===' to compare with 'null'.
4924 | 29 | Use '===' to compare with 'null'.
4929 | 20 | Use '===' to compare with 'null'.
5508 | 26 | Use '===' to compare with 'null'.
5509 | 35 | Use '!==' to compare with 'null'.
5806 | 35 | Use '!==' to compare with 'null'.
5963 | 38 | Use '!==' to compare with 'null'.
5978 | 39 | Use '===' to compare with 'null'.
5979 | 47 | Use '===' to compare with 'null'.
6450 | 24 | Use '===' to compare with 'null'.
6702 | 42 | Use '!==' to compare with 'null'.
6702 | 84 | Use '===' to compare with 'null'.

**Comment by bamoha** [comment]
Hello, I am yet to understand this issue, do you mean that one should go into the official Jquery source code and make these changes?

**Comment by thisisayush** [comment]
@Geekcoder555 `jquery.js` is an official library, this issue should be created at https://github.com/jquery/jquery not here.
