### ISSUE TITLE
Errors in file bootstrap.js

### ISSUE THREAD

**Issue by Geekcoder555** [internetarchive/wayback-machine-chrome#108]
Description:

The following errors are found in File bootstrap.js

Line | Col | Errors   bootstrap.js
-- | -- | -- 
6 | 317 | Missing semicolon.
6 | 615 | Missing semicolon.
6 | 715 | Missing semicolon.
6 | 775 | Expected an assignment or function call and instead saw an expression.
6 | 776 | Missing semicolon.
6 | 805 | Missing semicolon.
6 | 1064 | Missing semicolon.
6 | 1066 | Expected an assignment or function call and instead saw an expression.
6 | 1067 | Missing semicolon.
6 | 1068 | Expected an assignment or function call and instead saw an expression.
6 | 1069 | Missing semicolon.
6 | 1126 | Possible strict violation.
6 | 1249 | Expected an assignment or function call and instead saw an expression.
6 | 1250 | Missing semicolon.
6 | 1252 | Missing semicolon.
6 | 1327 | Missing semicolon.
6 | 1462 | Missing semicolon.
6 | 1557 | Expected an assignment or function call and instead saw an expression.
6 | 1836 | Expected an assignment or function call and instead saw an expression.
6 | 1837 | Missing semicolon.
6 | 1837 | Expected an assignment or function call and instead saw an expression.
6 | 1951 | Missing semicolon.
6 | 2013 | Expected an assignment or function call and instead saw an expression.
6 | 2014 | Missing semicolon.
6 | 2071 | Possible strict violation.
6 | 2229 | Expected an assignment or function call and instead saw an expression.
6 | 2230 | Missing semicolon.
6 | 2232 | Missing semicolon.
6 | 2327 | Expected an assignment or function call and instead saw an expression.
6 | 2328 | Missing semicolon.
6 | 2506 | Use '===' to compare with 'null'.
6 | 2587 | Use '===' to compare with 'null'.
6 | 2764 | Expected an assignment or function call and instead saw an expression.
6 | 2765 | Missing semicolon.
6 | 2774 | Expected an assignment or function call and instead saw an expression.
6 | 2775 | Missing semicolon.
6 | 3238 | Expected an assignment or function call and instead saw an expression.
6 | 3239 | Missing semicolon.
6 | 3348 | Expected an assignment or function call and instead saw an expression.
6 | 3349 | Missing semicolon.
6 | 3349 | Expected an assignment or function call and instead saw an expression.
6 | 3468 | Missing semicolon.
6 | 3789 | Expected an assignment or function call and instead saw an expression.
6 | 3790 | Missing semicolon.
6 | 3961 | Missing semicolon.
6 | 3962 | Expected an assignment or function call and instead saw an expression.
6 | 3963 | Missing semicolon.
6 | 4020 | Possible strict violation.
6 | 4272 | Expected an assignment or function call and instead saw an expression.
6 | 4273 | Missing semicolon.

Acceptance criteria:
The above file should be modified to correct above mentioned errors.

Time:
10-15 min

**Comment by divyabaid16** [comment]
@AnkitKhatri55555 , can you please elaborate what changes need to be done when you are saying- "Expected an assignment or function call and instead saw an expression."

**Comment by rohitcoder** [comment]
@AnkitKhatri55555  Are you sure? :confused: because bootstrap.min.js is official bootstrap library provided by "Bootstrap open source" Program and lot of companies and developers are using this same js script so there is no change of such type of problems or errors. Problem is in another file may be in any custom js file written by Wayback machine, not in bootstrap.min.js 
No chance

Simply copy & paste all codes of bootstrap.js (firstly copy & run js codes from jquery file) and run it in the console you will not get error which proves file isn't wrong.

**Comment by thisisayush** [comment]
@Geekcoder555 This doesn't seem to be an issue on my end. Are you sure? 
Please verify and see if this issue can be closed?
