### ISSUE TITLE
Incorrect extraction of URL

### ISSUE THREAD

**Issue by A7xSV** [internetarchive/wayback-machine-chrome#125]
Using the extension on a link such as this - [https://twitter.com/search?q=github.com/internetarchive/wayback-machine-chrome](https://twitter.com/search?q=github.com/internetarchive/wayback-machine-chrome) opens up the correct page by clicking Whois on the extension but Alexa extracts the wrong URL (github.com instead of twitter.com).

I would like to work on fixing this and other issues, along with adding more required features for the extension as part of Google Summer of Code 2018.

**Comment by anishsarangi** [comment]
Thank you for pointing out this issue. We have fixed this recently. Thank you!!
