### ISSUE TITLE
Bootstrap's JavaScript requires jQuery

### ISSUE THREAD

**Issue by rgpt** [internetarchive/wayback-machine-chrome#13]
"**Uncaught Error**: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6"
If you check for Errors you will notice that bootstrap.min.js needs minified jquery script

**Comment by gureks** [comment]
Issue resolved with PR #14

**Comment by rgpt** [comment]
JavaScript is being used to make the extension look faster so closing this issue
