### ISSUE TITLE
GSoC Rules for Contributing

### ISSUE THREAD

**Issue by oliveratutexas** [internetarchive/wayback-machine-chrome#19]
Hey there. I was thinking about expanding some of the social media features for this extension. I was wondering if there were any standards or rules that you guys have for contributing before I started.

**Comment by rgpt** [comment]
I think Issues are for any problems that exist in our project so we could resolve them.
 If you have any queries i request you to kindly clear them using their mailing list **info@archive.org**
I hope it helps :)
