### ISSUE TITLE
Coverting to React 

### ISSUE THREAD

**Issue by himanshuc3** [internetarchive/wayback-machine-chrome#255]
As you already guessed, this is more of a preference than an issue. But I did not know where else to discuss, So maybe this thread could be a solution. I could 1st of all understand the codebase and start implementing if needed. 

Also, this gives us an opportunity to reinvent design and make it cleaner.

**Comment by cgorringe** [comment]
React is likely overkill. We redid the design anyhow just with plain html / css!
