### ISSUE TITLE
Exclude website(s) feature

### ISSUE THREAD

**Issue by Manu1400** [internetarchive/wayback-machine-chrome#283]
Hi,

I want to can excluded website(s) on my instance.

**Comment by mkfeuhrer** [comment]
Can you specify a bit clearly with the feature you want. Thanks

**Comment by Manu1400** [comment]
On some website implements a redirect function who redirect 404 on homepage.

I want to can disabled the Wayback Machine extension on Chrome on a website.

Like an Adblocker, we can have a personal "blacklist" to exclude a website with a button "I want to exclude this website".

**Comment by VishvaWang** [comment]
> On some website implements a redirect function who redirect 404 on homepage.
> 
> I want to can disabled the Wayback Machine extension on Chrome on a website.
> 
> Like an Adblocker, we can have a personal "blacklist" to exclude a website with a button "I want to exclude this website".

hi  !,do you want to disable this extension in some website?what is the  redirect function who redirect 404 on homepage.

**Comment by JohnTitor42** [comment]
Can you tell, what you expect to be shown instead of the site?

**Comment by Manu1400** [comment]
https://fr.wikiversity.org/wiki/Sp%C3%A9cial:Suivi_des_liens?hidebots=1&hidecategorization=1&hideWikibase=1&target=SPARQL_Protocol_and_RDF_Query_Language%2FRequ%C3%AAtes_de_lecture&limit=50&days=7&urlversion=2 return HTTP 404. The wayback machin popin is opened but it this case it's not a real error 404 webpage.

**Comment by sr6033** [comment]
is this feature required? @MaxReinisch
