### ISSUE TITLE
opening of new save tab on clicking recent/first version buttons

### ISSUE THREAD

**Issue by pkarira** [internetarchive/wayback-machine-chrome#3]
When recent/first version buttons are clicked after clicking on the save button then another tab opens which also does the same work as of save which means that now there are two tabs for saving in archieve .

**Comment by Adi918** [comment]
I want to work on this issue but the extension is of version 1.3.2 and the code present here is of version 1.2. Can you please update the repository.

**Comment by PARAG00991** [comment]
@Adi918 You can pull the v1.3.3 branch meanwhile for the work. It has the update code, I guess.

**Comment by gureks** [comment]
You can find the relevant code here:
https://github.com/internetarchive/wayback-machine-chrome/tree/v1.3.3

**Comment by Adi918** [comment]
Can you give some more clarity about the issue pls

**Comment by pkarira** [comment]
Go to any page , click on Save Page Now button from chrome extension you will that a new tab opens up for saving . Now go back to that page and now click on Recent or First Version button , then you find that those buttons work but a new tab opens up for saving the page so now there would two tabs for saving the page . Try it yourself , you will find the error . I have resolved this issue in my pull request here https://github.com/internetarchive/wayback-machine-chrome/pull/4

**Comment by GaurangTandon** [comment]
Hi, it seems this issue has been fixed. Can it be closed? Clicking on Save page now redirects to `web.archive.org/save/*`, while clicking on recent version redirects to `web.archive.org/web/2/*`, both as intended. Clicking recent version no longer saves the page.
