### ISSUE TITLE
New feature: Dark mode

### ISSUE THREAD

**Issue by cheevu-RS** [internetarchive/wayback-machine-chrome#302]
I was thinking that it would be cool to add a dark themed mode throughout the extension using css's invert filter on styles.css. It can be added as an option in the settings.
I can put a PR for this if the mentors are fine with this addition.

**Comment by MaxReinisch** [comment]
Adding a dark mode is a cool idea, but using the invert filter might not be the best way to do it.  Check out the archive.org homepage and maybe try to copy the color scheme of that.  Also maybe this feature would best live in css/common.css

**Comment by cheevu-RS** [comment]
Sure, will do that. Thanks!

**Comment by cheevu-RS** [comment]
@MaxReinisch You want me to add the color scheme of archive.org as the dark theme?

**Comment by cheevu-RS** [comment]
@MaxReinisch The archive.org webiste only has a grey white theme.
![image](https://user-images.githubusercontent.com/33937406/55274162-5e11bb00-52fb-11e9-8946-702af7077d5c.png)
What i am suggesting is more like..
![image](https://user-images.githubusercontent.com/33937406/55274158-420e1980-52fb-11e9-8ec4-d29a9393775c.png)
 It is a bit crude, but i can fix that.

**Comment by sr6033** [comment]
Dark mode is really cool and keeping it in sync with the Internet Archive's theme is a nice idea. Nice work @cheevu-RS 
I will suggest you edit the logo as per the theme and also to choose such a colour that the texts are more clear.

**Comment by cheevu-RS** [comment]
Sure, thanks @sr6033!

**Comment by ZaidBJ** [comment]
@MaxReinisch , can I take up this issue

**Comment by anishsarangi** [comment]
This feature we are currently implementing!!
