### ISSUE TITLE
New feature: Donation button

### ISSUE THREAD

**Issue by radicalswetank** [internetarchive/wayback-machine-chrome#304]
I think the addition of a Donation button which will open [Donate to the Internet Archive!](https://archive.org/donate/) in a new tab can be a great idea!
@mentors if you guys agree can I put a PR?

**Comment by radicalswetank** [comment]
@vbanos Something like this!
![support_us](https://user-images.githubusercontent.com/26973191/55294773-9ad8d180-5423-11e9-978b-75e36e273edf.png)

**Comment by MaxReinisch** [comment]
I suggest putting the donation button between the feedback and the info button in the bottom tray.

**Comment by sr6033** [comment]
@cheevu-RS has done a PR regarding this issue #327
