### ISSUE TITLE
Convert XMLHttpRequest to AJAX

### ISSUE THREAD

**Issue by akkywadhwa** [internetarchive/wayback-machine-chrome#306]
I think converting XMLHttpRequest to AJAX will be a significant change and would cut down the lines of code. Should I make a PR for it?

**Comment by thisisayush** [comment]
The project is already using jQuery, I guess it would be logical to convert Javascript's XMLHttpRequest to a more stable jQuery Ajax Implementation.

**Comment by MaxReinisch** [comment]
The only issue with that is if it is running in background.js, as jquery is
outside the scope of that for some reason. You can either go into the
manifest and add build.js (I think, I am away from my computer so this
should be double checked), or you can use the js fetch api, which gets used
in several spots inside the background script. I am currently going theough
all the Requests and documenting them.

**Comment by cheevu-RS** [comment]
@MaxReinisch Can I work on this?

**Comment by MaxReinisch** [comment]
sure @cheevu-RS
