### ISSUE TITLE
UI Update

### ISSUE THREAD

**Issue by thisisayush** [internetarchive/wayback-machine-chrome#309]
The UI of popup box seems quite old, I'm suggesting some changes (PR for the same is on the way):
- Outline Buttons: These buttons fill up the background on hover/focus)
- Borderless Searchbar: This only includes a search bar with bottom border which gets dark on focus
- Custom Webkit Scrollbar: A thin scrollbar with rounded corner to maximise available popup space.

Preview:
![image](https://user-images.githubusercontent.com/22245433/55231712-788b5c00-5249-11e9-9fe0-66bee9f0e235.png)

**Comment by anishsarangi** [comment]
Good work @thisisayush . Can you suggest some more designs where we would not be using any scrollbar? (But it should also include all the features)

**Comment by thisisayush** [comment]
Thanks @anishsarangi
Yes, we can go for responsive designing, since chrome extensions do not support media queries, we have to do it the JavaScript way. We can adjust the width of the popup for a 2 column layout and more, in case the width is small, we can increase the height, and as a fallback when both are not feasible, scrollbar comes to the rescue.

Also the social icons can be moved to top right (with decreased height) and logo to top left.

If space is the issue, the buttons like "Load Recent Verson", "Load First Version" and "Browse all versions" can be clubbed together into a single drop-down button, so user can select what version to load from dropdown.

**Comment by Ritvyk** [comment]
@thisisayush Hey buddy i have added a instagram button on the UI hope you will like it.
Can we work together on this project to enhance it more.

**Comment by thisisayush** [comment]
I also love the UI made by @sr6033 in #333
