### ISSUE TITLE
Question regarding the search box

### ISSUE THREAD

**Issue by Zerichen** [internetarchive/wayback-machine-chrome#312]
Hi everyone, 
I found that the search box in the chrome extension didn't work on my computer and I am wondering if it is designed to allow the user to perform a search action. I have checked the source code and there was neither action nor method attribute in the form tag so I am assuming this is not being considered a feature at present. 
If you want me to add this feature, I can make a PR for it.

**Comment by MaxReinisch** [comment]
Currently the search bar is used basically as an alternative omnibox/address bar.  Features check if the user entered anything in the search bar, and the feature will use whatever is in the text box as the url instead of what is in the address bar.  

This is a feature that we have been investigating to see if it is used much.  It is not super useful, intuitive, or important.  But if you want to play around with the functionality, I would love to see it utilized in a better way than how we currently are using it.

**Comment by Zerichen** [comment]
Thanks for the explanation! At present, I think we could make the functionality the same as the search box in the Wayback Machine homepage. So the user can either type a keyword or a valid URL and then we can present the search result in a new tab. Having said that, I will continue exploring the new possibilities for this functionality as well. 

I am also thinking about adding a hyperlink to the Internet Archive logo so that the user can go to our homepage by simply clicking the logo, which seems very intuitive to me.

**Comment by Zerichen** [comment]
> Currently the search bar is used basically as an alternative omnibox/address bar. Features check if the user entered anything in the search bar, and the feature will use whatever is in the text box as the url instead of what is in the address bar.
> 
> This is a feature that we have been investigating to see if it is used much. It is not super useful, intuitive, or important. But if you want to play around with the functionality, I would love to see it utilized in a better way than how we currently are using it.

**Comment by sr6033** [comment]
> I am also thinking about adding a hyperlink to the Internet Archive logo so that the user can go to our homepage by simply clicking the logo, which seems very intuitive to me.

@Zerichen this seems pretty useful to me as well

**Comment by Zerichen** [comment]
@sr6033 Glad to hear that! You can add this to your new Ui as well. For me I am just going to stick with the current interface. We can also explore the search box functionality together if you want.

**Comment by sr6033** [comment]
@Zerichen my new UI is an experiment and I have kept it in a different branch for the maintainers to comment on it. It would be great to explore the search box functionality from now.

**Comment by Zerichen** [comment]
@sr6033 Cool
