### ISSUE TITLE
amazon books currently makes the same request twice

### ISSUE THREAD

**Issue by MaxReinisch** [internetarchive/wayback-machine-chrome#314]
Amazon books functions similarly to how auto-save used to function.  In background.js, every time a page gets updated, it checks if the page is amazon, and that the amazon setting is enabled.  Then it requests the https://archive.org/services/context/amazonbooks api and if a result is returned, it changes the extension badge.  Then in the popup script, it checks that the badge is changed, then makes the request again, then generates the button.  

Any time a feature makes the same request twice is an issue.  This can be handled similarly to how auto-save was changed.

**Comment by radicalswetank** [comment]
@MaxReinisch Can I put a PR on this?

**Comment by MaxReinisch** [comment]
@radicalswetank Go for it.  I won't be able to look at it until morning (pct).

**Comment by Zerichen** [comment]
Can I work on these bugs as well? @MaxReinisch

**Comment by Zerichen** [comment]
> Amazon books functions similarly to how auto-save used to function. In background.js, every time a page gets updated, it checks if the page is amazon, and that the amazon setting is enabled. Then it requests the https://archive.org/services/context/amazonbooks api and if a result is returned, it changes the extension badge. Then in the popup script, it checks that the badge is changed, then makes the request again, then generates the button.
> 
> Any time a feature makes the same request twice is an issue. This can be handled similarly to how auto-save was changed.

Hi @MaxReinisch , I am currently working on this issue and I think we could store the url after the first fetch and using ```chrome.storage.sync.set({ 'details_url': resp['metadata']['identifier-access'] }, function () { console.log('url is set to:', resp['metadata']['identifier-access'])}) ``` and retrive it in the borrow_books function by calling ``` chrome.storage.sync.get(['details_url'], function (result) { console.log('result is', result.details_url) })```. Is there any further concerns of doing so that I haven't noticed?

**Comment by radicalswetank** [comment]
@MaxReinisch Zerichen  has already put a PR on this. I guess this should be closed now.

**Comment by MaxReinisch** [comment]
@radicalswetank Not so, the PR introduced a bug and has been reverted. The issue is still live

**Comment by sr6033** [comment]
I think @Zerichen fixed the issue now.
