### ISSUE TITLE
Moving wikipedia books api request out of content script

### ISSUE THREAD

**Issue by MaxReinisch** [internetarchive/wayback-machine-chrome#315]
In wikipedia.js, the function getWikipediaBooks makes an ajax request to the context api.  According to https://developer.chrome.com/apps/xhr, this should not be done in a content script, and the request should be moved to background.js and use message listeners.  A similar problem was fixed in citations.js, which can be used as reference.

**Comment by radicalswetank** [comment]
@MaxReinisch Can I work on this one?

**Comment by MaxReinisch** [comment]
@radicalswetank Go for it.

**Comment by radicalswetank** [comment]
@MaxReinisch Zerichen has already put a PR on this. I guess this should be closed now.
