### ISSUE TITLE
Wikipedia papers isn't working right

### ISSUE THREAD

**Issue by MaxReinisch** [internetarchive/wayback-machine-chrome#316]
On the page: https://en.wikipedia.org/wiki/Nan_Madol, using the "Find cited papers" feature has a UI bug.  I am also wondering if this should make the API call in background.js like how wikipedia.js should be  #315

**Comment by cheevu-RS** [comment]
@MaxReinisch can i work on this? I will work on the bug part and not move the api call to background.js as someone else is working on it.

**Comment by MaxReinisch** [comment]
@cheevu-RS Go for it.  In this case, the API call shouldn't need to be moved, and if we decide to move it, it should be done after the UI fix anyways.  The issue someone else is working on is a different API endpoint for books instead of papers.
