### ISSUE TITLE
Arrow Keys are not working in autosuggestion List

### ISSUE THREAD

**Issue by Ritvyk** [internetarchive/wayback-machine-chrome#332]
Arrow keys become unresponsive in the dropped down auto suggestion list and list get vanished when try to use a arrow key.

**Comment by sr6033** [comment]
I think it is a bootstrap issue.

**Comment by Ritvyk** [comment]
@sr6033 i Think it so.

**Comment by tanweer919** [comment]
Fixed the issue and created a PR #337
