### ISSUE TITLE
[GSoC] Discussions

### ISSUE THREAD

**Issue by thisisayush** [internetarchive/wayback-machine-chrome#334]
I sent a mail to mentioned email a few days back, doesn't seem to get a reply, and since there is no official forum/chat available for the project, I guess using this issue seems to be a good place where everyone can share and discuss their doubts with mentors and other participants.

**Comment by thisisayush** [comment]
## [GSoC] Idea # 1 Creating/Improving UI of the chrome extension of Wayback Machine

Hi Mentor(s),
Myself Ayush Agarwal, B.Tech (CSE) 3rd Year, Amity University, Noida. I'm a full stack web developer jQuery/React/Bootstrap (Frontend), Django/Flask (Backend) and Dev-Ops (AWS/Ansible/Shell Scripting) and have been working on the web for more than 2 years now.

I'm thinking to create a new UI of the chrome extension of Wayback Machine based on Google's Material UI to blend it's UI natively with Chrome and also smoothen the UX as well add more features to the extension as a part of GSoC

For the UI, it will include updating Popup UI, annotations and other pages.

Any guidance regarding the same would be helpful.

Regards,
Ayush Agarwal

**Comment by Ritvyk** [comment]
@thisisayush  same here buddy, no reply from the Mentors or from that mail that is mentioned in the GSOC-19 Guide.

**Comment by thisisayush** [comment]
Well, I didn't get on GSoC this year, seems the slots were less so the extension didn't make it to the idealist. Nevertheless, congrats to all those who got selected :) Keep Trying, Keep Contributing!

Also, I would like to keep this one open, since there is no link to carry out any communications with the community, we can use this till then.

Thanks @MaxReinisch for the support and help :)

**Comment by sr6033** [comment]
Yes. I also think that the slots provided by Google were less and so the extension didn't appear. I agree with you for keeping this open.

Thanks to all for helping out. Also, works are left which need to be completed.
