### ISSUE TITLE
Add Support to check if any Contexts are selected before sending 'showall' message

### ISSUE THREAD

**Issue by thisisayush** [internetarchive/wayback-machine-chrome#339]
The `showall` message is sent even when there are no contexts selected or initialized. This results in poor UX as first-time users may wait thinking something will happen.
What we can do is add a check before sending the message and showing a message to user if no contexts are selected.

**Comment by sr6033** [comment]
I have included that in my new UI already.

**Comment by sr6033** [comment]
This is a nice addition to the UX for new users. I was adding that in the experimental UI as well. Good work @thisisayush 

You can also integrate this into your new UI, I think.

**Comment by MaxReinisch** [comment]
@thisisayush is right, @sr6033.  It is better to make these changes separately from the UI changes.  I understand that this change does fall under the category of UX, it is still more of a bug fix than a design change.

**Comment by sr6033** [comment]
Yup. Also, what @MaxReinisch suggested in the PR can be looked into after some thoughts.
