### ISSUE TITLE
Twitter search in show me context can be improved

### ISSUE THREAD

**Issue by Zerichen** [internetarchive/wayback-machine-chrome#346]
In show me context, we are trying to help the user to search the URL of the current tab on Twitter. However, I find this feature more useful if we could first extract the keyword from the URL and then perform a search. For example, if I am on Apple's homepage, instead of searching 'www.apple.com', we could search 'Apple' which obviously have much better search results.

**Comment by MaxReinisch** [comment]
I have thought the same thing, however I believe the intention of context features is to gain information about specific urls.  Originally, we were looking for an annotation system for urls.  We wanted to see what people thought about specific links.  Then we realized twitter could be used that way.  That is why this feature behaves this way.

**Comment by Zerichen** [comment]
Sure, I can fully understand its original intention.
