### ISSUE TITLE
Better documentation of features available

### ISSUE THREAD

**Issue by tanweer919** [internetarchive/wayback-machine-chrome#347]
The current version of the extension contains many features whose purpose are hard to understand at first glance like context features, visual site map etc. Unless you randomly click on the feature or dig deep within the extension, you may not be able to understand its purpose. So better documentation is required.

**Comment by sr6033** [comment]
I think this can be solved with better UX as well. But as a beginner standpoint view, good documentation is important. I agree. Let's work on it.

**Comment by tanweer919** [comment]
Cool, lets make it work.

**Comment by thisisayush** [comment]
And here comes my idea of First Run :P
