### ISSUE TITLE
Ideas for better "Show me Context" UX.

### ISSUE THREAD

**Issue by MaxReinisch** [internetarchive/wayback-machine-chrome#348]
There was a great discussion over at #340 about how to best improve the UX of this feature, as it has been a problem for a while.  Please continue that conversation here if you'd like.

**Comment by sr6033** [comment]
@MaxReinisch I am working on an idea for that. Will show the UI soon.

**Comment by Ritvyk** [comment]
I was thinking to add voice command feature.
**say -> "save this page as <name>" and the page will be saved in the archive.**
we could add more commands its just the matter of discussion over it.
Would you like to approve this idea or discuss over it..
_i have also created the prototype for this functionality._

**Comment by anishsarangi** [comment]
This thing is already implemented !! We can close this Issue !!
