### ISSUE TITLE
Improving Error Page Handling

### ISSUE THREAD

**Issue by thisisayush** [internetarchive/wayback-machine-chrome#366]
Right now, the extension catches any error code except 200 to show a wayback machine popup to see the most recent version of the page. This needs to be improved, for e.g. checking if a saved copy is available before showing the screen and also checking it for specific error codes, checking for 401 Unauthorised makes no sense.

Also, the UI for the dialog also needs to be improved, and instead of redirecting to the page, a better way would be to inject a full screen popup so that user can still have the reload feature.

**Comment by MaxReinisch** [comment]
I agree that the 404 feature does feel clunky.  It really should only run on 404's and you are right that it's bad to show dialog before checking if we have the page.  I'm not sure if showing a full screen popup is the best way, maybe have a more subtle notification in the extension.  If anyone has used the Honey extension, I think they usually have a dialog open on checkout on a store page that is pretty nice UI (but I should double check this)

**Comment by thisisayush** [comment]
404 will do, but before showing the popup, a simple quick ajax call to check if the page's archive is available would be good.

**Comment by ZaidBJ** [comment]
hi
I would like to take up this issue

**Comment by thisisayush** [comment]
@ZaidBJ Sure. Keep us posted, ping if you need any help.
