### ISSUE TITLE
cursor should change to pointer when hovered over social media icons

### ISSUE THREAD

**Issue by 9devilal** [internetarchive/wayback-machine-chrome#428]

**Comment by ZaidBJ** [comment]
@9devilal  i guess this has been done intentionally for a better user experience

**Comment by 9devilal** [comment]
@ZaidBJ maybe . thanks for commenting  :)

**Comment by Jayaprakashkumar** [comment]
Hello, I would like to work on this issue. I'm very new to this GSOC and open-source project. I fix this issue. I am trying to raise new PR, but it seems to access denied. Would you help me to get access and do further contributions

**Error:**
remote: Permission to internetarchive/wayback-machine-chrome.git denied to Jayaprakashkumar.
fatal: unable to access 'https://github.com/internetarchive/wayback-machine-chrome.git/': The requested URL returned error: 403

**Comment by cgorringe** [comment]
The issue's been fixed now, thanks!
