### ISSUE TITLE
Google plus social media icon is unnecessary.

### ISSUE THREAD

**Issue by karn21** [internetarchive/wayback-machine-chrome#430]
Since Google+ service has been closed by google for personal use, there should not be an icon for the same.

1. Click on extension icon
2. See the social media icons

**Expected behavior**
There should not be Google+ icon

**Screenshots**
![Annotation 2020-02-24 211609](https://user-images.githubusercontent.com/50626492/75167184-fd794100-574a-11ea-9e46-b21d17b09985.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Any

**Comment by srajgure** [comment]
@karn21  I think Chrome Webstore has the previous version of Wayback machine. The google plus icon is removed in the current master branch. So there is no need for a change.
![wayback2](https://user-images.githubusercontent.com/36104964/75268427-7e087200-581d-11ea-869e-a4e963519448.png)
