### ISSUE TITLE
"Share with Twitter" just opens twitter home page.

### ISSUE THREAD

**Issue by srajgure** [internetarchive/wayback-machine-chrome#436]
**Description**
"Share with Twitter" just opens the twitter homepage. Unlike other sharing options that directly allow the user to share the page as a post. 

**To Reproduce**
1. Go to any webpage you would like to share.
2. Click on 'Share with Twitter'
3. You will be redirected to Twitter homepage.

**Screenshot**
![image](https://user-images.githubusercontent.com/36104964/75411914-e9019800-5946-11ea-89a1-b38f38ea7606.png)

**Expected behavior**
After clicking on "Share with Twitter" a tweet intent should be called.

**Desktop (please complete the following information):**
 - Browser [e.g. Chrome ]

**Comment by Infinity-Intellect** [comment]
Can I work on this, or has this already been fixed?

**Comment by srajgure** [comment]
@Infinity-Intellect  It's been fixed.

**Comment by ZaidBJ** [comment]
why the extension live on chrome store and the one in the master branch are different(UI and some features)
