### ISSUE TITLE
Removal of Google+ from the Wayback Machine chrome extension.

### ISSUE THREAD

**Issue by shrenikr235** [internetarchive/wayback-machine-chrome#439]
Google+ has been shut down for almost a year now. The share icon on the chrome extension just redirects to a "Google+ has been shut down" page. I've edited popup.js and index.html from the chrome extension directory and everything looks good. I'm new here so any input is appreciated.

**Comment by karn21** [comment]
The version on chrome webstore is older. In the newer versions it has been removed. For reference see this [issue](https://github.com/internetarchive/wayback-machine-chrome/issues/430#issue-569945391).

**Comment by shrenikr235** [comment]
Thanks for the update @karn21
