### ISSUE TITLE
Listing for Microsoft Edge (chromium version)

### ISSUE THREAD

**Issue by superusercode** [internetarchive/wayback-machine-chrome#441]
**Is your feature request related to a problem/ issue? Please describe.**
Make the wayback machine extension available on the edge addons store. Edge is now based on chromium and no longer requires additional work to convert the extension. Existing users can install straight from the CWS, but this would be more convenient.

**Describe the solution you'd like**
There is no work to port the extensions since the new edge is based on chrome. All users on Windows/macOS (and Linux in the near future) are already able to install it from the chrome web store when prompted to enable downloads from the CWS. The extension submission process is detailed at https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension

**Comment by msaaddev** [comment]
Hey, @superusercode! I don't think it will be that easy since there is still a lot of Web API functionality Edge [does not support](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs). Though it is still possible, it will need some work.

**Comment by superusercode** [comment]
@msaaddev that comparison has not been updated to reflect that edge is now based on chromium (notice that the icon still uses the old logo)

old:
![image](https://user-images.githubusercontent.com/60588434/77228152-cafd1100-6b5b-11ea-922c-eda7f159305a.png)


new:
![image](https://user-images.githubusercontent.com/60588434/77228162-d7816980-6b5b-11ea-874a-0315cb483c39.png)

if you do notice any concerns, please let me know so i can notify the developers through the chromium bug tracker

**Comment by superusercode** [comment]
I have been using the extension perfectly by installing it from the chrome web store at the moment
![image](https://user-images.githubusercontent.com/60588434/77228192-0d265280-6b5c-11ea-9c54-27f40fc54dc1.png)
