### ISSUE TITLE
Enter button in the search section does not work

### ISSUE THREAD

**Issue by pranshukharkwal** [internetarchive/wayback-machine-chrome#443]
**Describe the bug**
The search option only works when you choose a site from the list of suggestions but the search option does not work when you type some word and press enter

**To Reproduce**
1. Click on the extension
2. Click on the search section and type anything
3. Press enter

**Expected behavior**
Search should take place on the basis of the word given, and take to the wayback site with the searched term.

**Desktop 
- OS: Windows 10
 - Browser: Chrome

**Comment by tikhsuP** [comment]
@pranshukharkwal  are you checking this functionality in the current version or in the previous version of the extension?
Google extension store has a previous version.

**Comment by pranshukharkwal** [comment]
@tikhsuP I was checking with the previous version. Can you please share the crx file for the current version, or am I supposed to check the current version by setting up the development environment

**Comment by tikhsuP** [comment]
@pranshukharkwal 
You can check it by installing the development environment, I am doing the same.

**Comment by cgorringe** [comment]
Since this issue only applies to the old version on the Chrome store, I'm closing this issue.
