### ISSUE TITLE
Uneven Margin in 'Tweets About This Page' button

### ISSUE THREAD

**Issue by tikhsuP** [internetarchive/wayback-machine-chrome#449]
**Describe the bug**

There is uneven top-bottom marginin the 'Tweets About This Page' button.
This is happening due to the Twitter Icon.
Although, all the buttons have been assigned the same height (30px), but the inclusion of this icon breaks the desired sizing of the 'Tweets About This Page' button.
This is because the class `.fa { margin-top: 6px; }` is applying this extra margin to the top of the Twitter icon.

**To Reproduce**

1. Go to 'Tweets About This Page' button
2. See error

**Expected behavior**

The padding should look equal.

**Screenshots**

![Screenshot (41)](https://user-images.githubusercontent.com/42881874/77839927-1be5b880-719f-11ea-9aa3-892dd31ed344.png)

**Desktop (please complete the following information):**

 - Windows 10
 - Chrome

**Comment by cgorringe** [comment]
Thanks, it's now been fixed.

**Comment by tikhsuP** [comment]
Yes, I checked the new UI, it looks great.
