### ISSUE TITLE
Flip-NOT WORKING: Code Improvement

### ISSUE THREAD

**Issue by tikhsuP** [internetarchive/wayback-machine-chrome#450]
**Describe the bug**

In [index.html](https://github.com/internetarchive/wayback-machine-chrome/blob/master/index.html) you can see that all the buttons are intended to flip, but only the 'Show Me Context' button is flipping.

 `<div class="flip" id="savebtn">...</div>  <div class="flip" id="recentbtn">...</div>  <div class="flip" id="firstbtn">...</div>  <div class="flip" id="allbtn">...</div>  <div class="flip" id="mapbtn">...</div>  <div class="flip" id="twitterbtn">...</div>`

This needs to be improved to work as intended.

**To Reproduce**

1. Go to any button
2. Hover over it
3. Doesn't flips

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome

**Comment by sanyam99ag** [comment]
@tikhsuP Flip functionality is only to display additional information. When the URL is not supported then it gets to show the particular piece of information. But when everything goes correctly it remains fixed since there is no info to show on that particular website.

**Comment by tikhsuP** [comment]
@sanyam99ag 
Yeah, I get that, thanks :)
But, I would like to check that flipping functionality, how do i do that?

**Comment by sanyam99ag** [comment]
Since URL without Http or Https is not supported.
so for example: If you are checking the current version then, when you will go to the about page of the latest version of the extension, you find the flip is working to show "URL Not Supported".

**Comment by tikhsuP** [comment]
Actually, I am facing some issues while setting up the environment locally.

![Screenshot (47)](https://user-images.githubusercontent.com/42881874/77957343-f963b480-72f0-11ea-8d59-cd4282e6c041.png)

I have made sure that the following code is included in my manifest.json file but the errors aren't solved:

`"permissions": [
    "storage"
  ],`
