### ISSUE TITLE
Add Share through EMAIL option

### ISSUE THREAD

**Issue by tikhsuP** [internetarchive/wayback-machine-chrome#451]
**Feature**
We can add a share through EMAIL button in the SHARE section.

![Screenshot (42)](https://user-images.githubusercontent.com/42881874/77849975-1c0ca500-71ed-11ea-8689-c3d0ade40936.png)

This adds another option to share and increases the functionality of the extension.

**Comment by tikhsuP** [comment]
The button can look like this:
![Capture](https://user-images.githubusercontent.com/42881874/79510994-0821c980-805c-11ea-91c8-b24c3eb2420e.PNG)

@anishsarangi sir, what are your thoughts?

**Comment by anishsarangi** [comment]
We don't have any feature like this in to-do list !
