### ISSUE TITLE
Mentioning the latest capture.

### ISSUE THREAD

**Issue by tikhsuP** [internetarchive/wayback-machine-chrome#473]
**Is your feature request related to a problem/ issue? Please describe.**
I was checking the latest version of the extension and after saving a page, I realized that there is more that can be done.
I felt the need to know/confirm if the page was saved or not. All I could investigate was that I had saved a page on that day, as the message was displayed on the flipped 'SAVE PAGE NOW' button.

I investigated the PRs for the mention of a similar issue and I found [this](https://github.com/internetarchive/wayback-machine-chrome/pull/422).

**Describe the solution you'd like**

As mentioned by @vbanos :

> UI observations using Windows 10 + Chrome 77:
> 
>     When I move my mouse over the "Save Page Now" button, I see "Last Saved: 2019-10-02"
>     If the date is today, it would be very helpful to show also the time (HH:MM). That's because there
>     could be multiple captures today. I may have done a capture just now and I want to see the latest
>     capture datetime to confirm I did it.

**Comment by cgorringe** [comment]
Yep, that was actually on my TODO list for today. I'm going to display the last saved TIME instead of the DATE if the last save occurred within the past 24 hours.

**Comment by tikhsuP** [comment]
That's great.
