### ISSUE TITLE
Mentioning the Date/Time for the Oldest and Newest version of saved webpage.

### ISSUE THREAD

**Issue by sanyam99ag** [internetarchive/wayback-machine-chrome#475]
**Is your feature request related to a problem/ issue? Please describe.**
According to the updated repository the page save status is being displayed on the flipped "Save Page Now" Button.
The feature that can be added is we can mention the respective Date/Time on the flipped "Oldest" and "Newest" Button. So the user will get to know about the oldest and the newest version of the webpage without checking that explicitly.

**Describe the solution you'd like**
It would be helpful to the user to show the respective Date/Time on the flipped "Oldest" and "Newest" Buttons

**Comment by tikhsuP** [comment]
That would be great.

**Comment by cgorringe** [comment]
Not sure if it'll fit well on the smaller buttons. I guess someone can try it and see.

**Comment by sanyam99ag** [comment]
@cgorringe Surely the date will fit in the button if we use the "YY/MM/DD" format.
&nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;        ![Oldest](https://user-images.githubusercontent.com/39384430/80859191-5221c680-8c7c-11ea-8fc8-f142ee824332.png) &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;    ![Newest](https://user-images.githubusercontent.com/39384430/80859189-50580300-8c7c-11ea-8f21-f8d9ec858ec2.png)

**Comment by tikhsuP** [comment]
I think we should follow the same pattern as in the Save Page Now button, as using a different pattern will confuse the user.
Also, the YYYY/MM/DD is the easiest to understand. The patterns like YY/MM/DD, DD/MM/YY, MM/DD/YY are more probable to be misunderstood.

Can we try a popup message with YYYY-MM-DD that shows up on hover?

**Comment by sanyam99ag** [comment]
That is a great recommendation to keep uniformity for better user experience.
So we can decrease the size of the calendar icon, so as to display the date in standard format i.e. YYYY/MM/DD

![Screenshot from 2020-05-03 00-29-05](https://user-images.githubusercontent.com/39384430/80873301-2979eb00-8cd5-11ea-9f8a-ddefdc27e2b5.png)

**Comment by cgorringe** [comment]
I'm not in favor of reducing the size of the calendar icon. If we're going to do this, I'd rather widen the buttons or shrink the font size of the date.

I'd suggest the date format be whatever the default locale is for the user. Example:
```
let d = new Date();
d.toLocaleDateString(undefined, {year: 'numeric', month: 'numeric', day: 'numeric'} ); // 5/2/2020
d.toLocaleDateString(undefined, {year: 'numeric', month: '2-digit', day: '2-digit'} ); // 05/02/2020
```

Also note that the "Newest" date is the same as the "Save Page Now" date, so would be redundant.

**Comment by cgorringe** [comment]
Perhaps we can do this as a tooltip (i.e. setting the "title" of the button.)
