### ISSUE TITLE
Checking of SHOW ALL CONTEXTS checkbox

### ISSUE THREAD

**Issue by tikhsuP** [internetarchive/wayback-machine-chrome#477]
**Describe the bug**
When the user clicks/checks the SHOW ALL CONTEXTS checkbox, all the context checkboxes get checked. Same happens when the user unchecks this checkbox, but, this checkbox should also get checked automatically if the user manually checks all other context checkboxes.

**To Reproduce**
1. Go to the CONTEXTS section in SETTINGS 
2. Check all the checkboxes other than SHOW ALL CONTEXT
3. See Error

**Expected behavior**
Checking all the individual checkboxes should check the SHOW ALL CONTEXTS checkbox.

**Screenshots**
![wbmc](https://user-images.githubusercontent.com/42881874/80701165-9b4b0c80-8afc-11ea-9654-9022f7e3863a.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 81.0.4044.122

**Additional context**
Since this checkbox doesn't get checked automatically, the user needs to uncheck the individual checkboxes if he wants to uncheck them all, or he needs to first check the SHOW ALL CONTEXTS checkbox and then uncheck it.

**Comment by tikhsuP** [comment]
Another way to express this issue is:
1. Check the SHOW ALL CONTEXTS checkbox
2. Uncheck any of the other checkboxes
3. The SHOW ALL CONTEXTS checkbox gets unchecked, as it should
4. Now check the same unchecked checkbox, the SHOW ALL CONTEXTS checkbox should get checked but it doesn't
5. See Error

**Comment by anishsarangi** [comment]
Nice @tikhsuP ! Thank you for pointing out this issue. Please feel free to make a PR :-)
