### ISSUE TITLE
Imporving the switch UI in Settings menu

### ISSUE THREAD

**Issue by tikhsuP** [internetarchive/wayback-machine-chrome#488]
**Is your feature request related to a problem/ issue? Please describe.**
I suggest this theme to make the Settings menu easier to understand, as right now it is a bit confusing to understand which button is selected.

![Capturehhhhh](https://user-images.githubusercontent.com/42881874/80936124-60432480-8ded-11ea-8d0b-7681c1589173.PNG)

**Comment by cgorringe** [comment]
I think this is a great improvement!

**Comment by anishsarangi** [comment]
I am tagging @markjohngraham here so that he can take a took. It is a great solution I think. 
Thanks @tikhsuP .
