### ISSUE TITLE
Calender to access archives of the website

### ISSUE THREAD

**Issue by HimanshuAttri** [internetarchive/wayback-machine-chrome#5]
A calender can be added to the chrome extension which will be similar to the calende shown here http://web.archive.org/web/*/facebook.com

Sample UI
![screen shot 2017-03-10 at 2 12 06 am](https://cloud.githubusercontent.com/assets/12981490/23770153/f835ec74-0537-11e7-905c-a0670f9384f2.png)

On selecting a date, different timestamps of the day would showup with link to their respective archive links. UI can be similar to this one.
![screen shot 2017-03-10 at 2 12 15 am](https://cloud.githubusercontent.com/assets/12981490/23770238/4ce2caee-0538-11e7-8375-ab4fdd0aa15b.png)

I have tried creating a similar chrome extension.
![screenshot from 2017-03-10 01-46-32](https://cloud.githubusercontent.com/assets/12981490/23770269/71647afc-0538-11e7-884e-fe8ad8c925e9.png)

@markjgraham and @rchrd2 Let me know what you think about it.

**Comment by epitron** [comment]
This would be a great addition!

From a usability perspective, I think it would be better to put the timeline chart in the pop-out window. The problem with the calendar is that it can only display one month at a time, and requires many clicks to get to a desired month. The timeline, on the other hand, shows the entire history at once, and with a single click, you can pick a date. I think the timeline has the right amount of precision for most use-cases.
