### ISSUE TITLE
Getting Tweets as Chrome Notifications

### ISSUE THREAD

**Issue by SerChirag** [internetarchive/wayback-machine-chrome#50]
I have been working for a while on implementing this feature.

OBJECTIVE : Get Twitter Search results as Chrome Notifications rather than opening them in a separate URL.
I believe this would over-all improve the User Experience as he/she would not loose continuity and would get relevant tweets as small notifications.

WHAT I HAVE TRIED :

1. Twitter REST API : 
The problem here is that Twitter REST API gives **date-based results** only for the last 7 days. This very much reduces the choice provided to the user.

2. This repository : https://github.com/Jefferson-Henrique/GetOldTweets-python
The problem here is the time required to fetch the tweet data. It is around 20 seconds, which is enough for any user to get mad. Plus the repository is pretty bulky.

3. The standard XML Request.
The response time is quick and it can be easily incorporated. 
Problem: Since the search results come as an infinite-scrolling page, it means that we can extract only the first 20 tweets using this method. Although I have tried to scroll down on the XML data page, but have not succeeded.

Anyone comments on this situation ? 
Anyone is free to contribute to implementing this feature

**Comment by anka-213** [comment]
I believe you have asked this in the wrong place. This is the issue-page for the Internet Archive's chrome extension, which has nothing to do with neither twitter nor push notifications.
