### ISSUE TITLE
"Enable 404 Not Found" Setting

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-chrome#506]
I'd like to see an "Enable 404 Not Found" item added to General Settings.
- When set, turns on Wayback Availability check when visiting a 404 page, and displays HTML popup. This is what currently happens.
- When not set, turn off the check (don't call API), and don't display popup.
- This should be set default ON when user runs extension for first time.

Here's a 404 link to test against:
http://purl.oclc.org/docs/inet96.html

**Comment by anishsarangi** [comment]
@cgorringe This is actually a main feature of our extension. Do you still want to mark it as a "option" for the user ?

**Comment by cgorringe** [comment]
Yes, but the option should be set to ON by default when the user first installs it. I've seen some reports on Safari, but also may occur on Chrome, where the 404 popup doesn't work properly or interferes with web browsing.

A couple of [reviews quoted from here](https://chrome.google.com/webstore/detail/wayback-machine/fpnmgdkabkmnadcjpehmlllkndpkmiak/reviews?hl=en):

> can u add an option to stop this "Page not available?"??? so annoying

> It works sometimes.
> It also works when it is not supposed to, like when Cloudflare decides to start harassing my browser.

On that second one, I've also had a report on the Safari extension, where Cloadflare interferes with the 404 popup. I haven't been able to recreate that particular bug in order to test it yet, although I did discover another website where the 404 feature did cause a problem on Safari.

So just in case there are websites that don't work properly with it turned on, I'd like to give the user an option to turn it off.

**Comment by mitchell-frost** [comment]
Can I work on this?

**Comment by anishsarangi** [comment]
@mitchell-frost I have already worked on this https://github.com/internetarchive/wayback-machine-chrome/pull/518.
Please feel free to pick up any other issues.
Thank you !

**Comment by mitchell-frost** [comment]
@anishsarangi sure! Thanks for the heads up.
