### ISSUE TITLE
Review and Reduce API calls + Privacy setting

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-chrome#507]
This idea here is to make more efficient by reducing API calls, and increasing privacy.

- Analyze API calls that are being made in the background.
  - How often? Are they excessive? Are the same calls being made repeatedly?
  - Can you find a way to reduce or cache repeated API calls?

- Add a Setting to top of General Settings, called "Private Mode".
  - This would work similar to "Show All Contexts" in that when checked, other items that use APIs such as "Wayback Count", "Auto Save Page", "Enable Relevant Archived Resources", "Auto-update Contexts", and "404 Not Found" will all be unchecked.
  - If user checks one of those, "Private Mode" will auto-uncheck.
  - Ensure that when "Private Mode" is checked, that no background API calls are made, even when user hovers over buttons, unless user explicitly clicks on a button (only then is it OK to make an API call.)

Dependent on #506 done first.

**Comment by cgorringe** [comment]
Here's an example API call that happens repeatedly.

An authentication check is done every time user taps toolbar icon and popup opens.

- POST to https://web.archive.org/save/ - with empty parameters.
  - fetched from auth_check() in background.js
  - which is called from checkAuthentication() in popup.js
  - which is called from last_save() in popup.js
  - which is called from checkExcluded() in popup.js
  - which is called from window.onloadFuncs[], every time popup displays.

- Could this be reworked so that the API call is only done once, then cached in a bool var?
  - May need to test for offline status?
  - Test every time browser closes and reopens, so don't store in persistent storage.

**Comment by mitchell-frost** [comment]
I am new to open source. Can I work on this?
