### ISSUE TITLE
Limited set of http status codes used

### ISSUE THREAD

**Issue by vbanos** [internetarchive/wayback-machine-chrome#519]
https://github.com/internetarchive/wayback-machine-chrome/blob/850f9e3b7338cb82d114a8b49b18099aa42792e4/scripts/background.js#L32

We use this list to check for problematic pages in one place.
Why don't we just check if `details.statusCode >= 400` ? The status could have a value that is not in this limited list, e.g. 501 or 401. It could be any 4xx or 5xx page.

**Comment by anishsarangi** [comment]
Thank you @vbanos . It would be better if we will use just `details.statusCode >= 400` rather than checking in the list. I will work on that. Thank you !
