### ISSUE TITLE
Inefficient list lookup for every page load

### ISSUE THREAD

**Issue by vbanos** [internetarchive/wayback-machine-chrome#520]
https://github.com/internetarchive/wayback-machine-chrome/blob/850f9e3b7338cb82d114a8b49b18099aa42792e4/scripts/background.js#L18

We need to see if the current host belongs to a list of news hosts. The news hosts are stored in a `list`.

When you do `newshosts.includes(other_host)`, you compare `other_host` with EVERY host in the list. This is not efficient. There are other datastructures, e.g. `Set` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set or `dict` https://pietschsoft.com/post/2015/09/05/javascript-basics-how-to-create-a-dictionary-with-keyvalue-pairs which do the lookup efficiently.

If this operation wasn't so common, I wouldn't mention this but it is happening on every page load so I think that this optimisation would be nice.

**Comment by cgorringe** [comment]
Although in practice comparing against this short list likely wouldn't be noticeable, but YES you're totally correct that the proper data structure is a dictionary or set. :-)

**Comment by anishsarangi** [comment]
Thank you @vbanos . Yes, the correct implementation would be using `set` or `dict` where the lookup will take constant time which is now taking `O(n)` in case of `list`.
Thank you. I will work on that.
