### ISSUE TITLE
The readme.md file needs revisions, addition of a proper contribution guide for new developers.

### ISSUE THREAD

**Issue by pranshukharkwal** [internetarchive/wayback-machine-chrome#531]
In my opinion, the readme.md file can be edited to improve the documentation so that the new contributors find it easy to start contributing. 
I would like to work on this issue and add few more points to the documentation. 
Here is a list of things that I intend to add to the documentation. I basically want to add a proper step by step contribution guide, which would contain these extra things, apart from those already present there.

1) Add steps for forking, cloning, proper way of making changes(using relevant branch names, and proper commits), and pushing the changes and making a pull request. 

2) Basic information about the tech stack used in the project, and the directory structure

3) Linking to relevant articles for installing Node.js and npm

4) Updating the features section, by removing the old (and non-existing features) and adding the newly added features

5) Adding a note for the new developers, that the version in the chrome web store is different from the current version, so the current version has to be used for development, and raising new issues. 

Anything else, which is necessary and is pointed out in the comments.

**Comment by pranshukharkwal** [comment]
@cgorringe Looking for a green flag, to start working on this issue

**Comment by cgorringe** [comment]
@markjgraham (our director) had assigned himself this issue, but I actually think it would be wonderful if you went ahead and worked on this @pranshukharkwal ! We can review it for edits during the pull request. There's some work already done on #325 which never got merged. Feel free to use some or all of that. I thinking having it as a separate contributor's guide file, then link or refer to it from the README, is a good idea.

Thanks, we appreciate the help!

**Comment by pranshukharkwal** [comment]
Thanks @cgorringe 
I am on it. 
Also, do we have a communication channel, to discuss things related to Wayback machine chrome extension, and internet archive in general? 
A slack workplace or something?

**Comment by cgorringe** [comment]
@pranshukharkwal Yes, we do use Slack to communicate, and you are welcome to join! Just email mark@archive.org and he will send you an invite.
