### ISSUE TITLE
"Show Features in Window" isn't working in Firefox

### ISSUE THREAD

**Issue by tikhsuP** [internetarchive/wayback-machine-chrome#536]
**Describe the bug**
When a Firefox user tries to see **Contexts** in a new window , the **Contexts Window** doesn't pops up.

**To Reproduce**
Open the extension in Firefox, then: 
1. Go to **"Contexts"** menu
2. Select one or more context(s) that you would like to see
3. Go to **"General"** menu
4. Set the  **"Show Features in"** option to **Window**
5. Click on the **"Show Contexts"** button in the extension
6. See error

**Expected behavior**
A window, showing the Contexts, should popup.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 76.0.1

**Comment by anishsarangi** [comment]
Thank you @tikhsuP for pointing this out !
I will make a PR resolving this issue !

**Comment by tikhsuP** [comment]
This issue can be replicated also by the following steps:
Open the extension in Firefox, then:
1. Set the **"Show Features in"** option to **Window**
2. Click on any of the following:
  a. Fb/Twitter/Linked Share options 
  b. Oldest/Overview/Newest buttons
  c. Sitemap/Related Tweets/ Show Contexts buttons
  d. Donate/About/ Feedback button
  e. Wayback Machine banner at the top
3. See error

**Comment by cgorringe** [comment]
Fixed in #535 and merged to master. Please test master, then close this issue if it works.

**Comment by tikhsuP** [comment]
Works well in both Firefox and Chrome. We can close this issue.
