### ISSUE TITLE
Incorrectly saving pages on web.archive.org

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-chrome#544]
**Describe the bug**

While visiting a page on **web.archive.org**, and logged out, hovering over SPN button will say "URL not supported" (correct), but then when clicked, it will try to Save, then a notification returns an error that you need to be logged in. After logging in, this will actually Save the page, even though it is not supposed to.

**To Reproduce**
 - Visit an archived page, such as: https://web.archive.org/web/20200609105857/https://www.iskme.org/
 - Click on "Save Page Now" button.

**Expected behavior**

Clicking on "Save Page Now" should not do anything.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Additional context**

I tested these URLs from excluded_urls, which do not have the same issue and work as expected:
- https://chrome.google.com/webstore/category/extensions
- http://localhost/
- http://127.0.0.1/
- chrome://version/
- The extension's About page (chrome-extension://.../about.html)

**Comment by tikhsuP** [comment]
> While visiting a page on web.archive.org, and logged out, hovering over SPN button will say "URL not supported" (correct), but then when clicked, it will try to Save, then a notification returns an error that you need to be logged in.

This is because it is not checking the login status if the URL is not supported.

**Comment by tikhsuP** [comment]
Why are we cleaning the URL in the `save_now()` function? 
https://github.com/internetarchive/wayback-machine-chrome/blob/master/scripts/popup.js#L54 
This is converting the "https://web.archive.org/web/20200609105857/https://www.iskme.org/" to " https://www.iskme.org" and saving it.

**Comment by cgorringe** [comment]
I think we probably shouldn't be cleaning the URL.
