### ISSUE TITLE
Add a Resource List Popup Window to SPN

### ISSUE THREAD

**Issue by cgorringe** [internetarchive/wayback-machine-chrome#549]
This is a feature to add to 'Save Page Now'.

The idea is to create a popup window that displays a scrolling text box, populated with the list of resources (URLs) as they are being retrieved from the SPN2 API during pending status.

Mainly duplicating what the website version does while logged in, but as part of the extension.
https://web.archive.org/save

Would also have a checkbox in Settings to enable.

This screenshot also displays Outlinks, but for now, just the resource list in the textbox should be a good start.
![SPN-resource-textbox](https://user-images.githubusercontent.com/604259/84372058-6e742580-ab8f-11ea-9d17-819d2e911dcb.png)

**Comment by anishsarangi** [comment]
@cgorringe Should we show the Resource List popup inside the extension popup ?

**Comment by cgorringe** [comment]
I would think that showing a list of URLs inside that 200px wide popup wouldn't be a very good experience for users. So no. It should display in a new window (or tab) similar to Show Contexts. (but likely a different window/tab than Show Contexts.)

**Comment by anishsarangi** [comment]
Thank you @cgorringe !
