### ISSUE TITLE
Chrome Extension dissapeared from Web Store

### ISSUE THREAD

**Issue by halogeno** [internetarchive/wayback-machine-chrome#581]
https://chrome.google.com/webstore/detail/wayback-machine/fpnmgdkabkmnadcjpehmlllkndpkmiak is showing 404 in Google Web Store.

**Comment by cgorringe** [comment]
Thanks, we're working on it!

**Comment by msikma** [comment]
Weird. Curious to hear what happened.

**Comment by cgorringe** [comment]
Google deleted it. We're trying to resubmit and restore the old page and hope we can get the same page back with the reviews intact, etc.

**Comment by anishsarangi** [comment]
The extension is again available in the store ! 
https://chrome.google.com/webstore/detail/wayback-machine/nbkhjdgdpjdebcniehkeigmdfeiokegh

**Comment by cgorringe** [comment]
FYI, the new Chrome Store link doesn't have the prior reviews & ratings and has a different ID (meaning it's being treated as a different extension.) We're still trying to get it restored at the old link / ID.

**Comment by halogeno** [comment]
Did Google deleted the Extension because of political correctness reasons?

**Comment by cgorringe** [comment]
It was more like they let a bot loose to enforce a permissions policy change, which we didn't get to fixing in time. Although their notice wasn't at all clear on what they expected us to do.

**Comment by cgorringe** [comment]
Although the OLD extension IS up on the Chrome Store under a new ID, we are still waiting to restore the old page and ID on the store, after which we'll take down the new page / ID.

**Comment by cgorringe** [comment]
Wow, this took WAAAY too long, but it's now back to the original link!
