### ISSUE TITLE
Social Sharing of First version

### ISSUE THREAD

**Issue by HimanshuAttri** [internetarchive/wayback-machine-chrome#6]
Social Media buttons for twitter, facebook etc can be added which would facilitate the sharing of the first version of the website being visited.

@markjgraham and @rchrd2 What do you think about it? I can start working on it right away, please let me know.

**Comment by prasadwajekar** [comment]
@markjgraham and @rchrd2 I would like to contributre to this issue

**Comment by GaurangTandon** [comment]
This seems to be fixed too. Now the popup has four social sharing buttons for Twitter, FB, G+, LinkedIn.
