### ISSUE TITLE
Add-on icon should distinguish between "URL Not Supported" and "This page was never archived"

### ISSUE THREAD

**Issue by tbayer** [internetarchive/wayback-machine-chrome#601]
When the extension icon shows that there are no saved versions of the page, it would be great if it could also indicate whether this is because the page can't be saved or just because it hasn't been saved yet - e.g. by greying out the icon in the "not supported" case.

**Comment by mitchell-frost** [comment]
Hey! I am new to the project. Can I work on this issue?
