### ISSUE TITLE
Quickly show if page previously saved

### ISSUE THREAD

**Issue by diegodlh** [internetarchive/wayback-machine-chrome#61]
The extension is awesome. Sometimes I use it to make sure I will be able to access the webpage I'm looking at in the future in case the owner decides to take it down. Some pages don't change frequently, so knowing that there is at least one version saved of it should be enough. To avoid overloading Internet Archive's servers with page snapshots, it might be useful to quickly inform the user, on the extension's popup, if there the page has been saved at least once in the past, or alternatively what is the last time that the page was saved, without having the user to access the overview page (as it would require that he/she visits another webpage). I'm afraid I'm not sure I have the time and knowledge to implement this. If you think it would be useful, it would be great if somebody could pick it up!

**Comment by markjohngraham** [comment]
I agree with you.  That feature is "on our list" :-)

**Comment by diegodlh** [comment]
Oh, I see now there are some pull requests implementing similar stuff. Sorry I didn't check before posting the issue! Thanks for your reply

**Comment by sr6033** [comment]
This is feature is already implemented and the issue should be closed. If a page is not saved, an 's' appears in the extension to let the user know.
#328

**Comment by anishsarangi** [comment]
This is feature is already implemented
