### ISSUE TITLE
Chrome Extension web store listing has been removed

### ISSUE THREAD

**Issue by darthwalsh** [internetarchive/wayback-machine-chrome#628]
**Describe the bug**
The link to the Chrome Web Store listing 404's

**To Reproduce**
https://chrome.google.com/webstore/detail/wayback-machine/fpnmgdkabkmnadcjpehmlllkndpkmiak

**Expected behavior**
I'd expect the wayback machine extension to activate and show me an archived version of the listing, but the extension has been unexpectedly removed from my chrome browser.

**Additional context**
Did Google suspend the extension for overly broad permission violation?

**Comment by cgorringe** [comment]
Yeah we know. See #581 
We're still working on it. It's slow...
