### ISSUE TITLE
Chrome Web Store link returns error message.

### ISSUE THREAD

**Issue by Avi-sa** [internetarchive/wayback-machine-chrome#644]
Chrome Web store link not working..

**To Reproduce**
1.Go to ' Read me'
2. Click on 'Chrome Web Store'
3. See error

**Expected behavior**
the link should take user to the chrome.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]

**Comment by cgorringe** [comment]
We know. We're working on restoring the extension on the chrome store. See #581
