### ISSUE TITLE
Code in background.js is not properly indented and formatted

### ISSUE THREAD

**Issue by bhavyaagg** [internetarchive/wayback-machine-chrome#73]
Hi I am Bhavya Aggarwal, currently in my Junior Year. I am Full Stack Web Developer in Node.js and currently also learning Android Development. 

@vbanos , @SerChirag I would love to work on this extension.

**Comment by anishsarangi** [comment]
Thank YOU @bhavyaagg for figuring this out. We have kept this issue on our "to-do-list".
