### ISSUE TITLE
Update Bootstrap 3 to Bootstrap 4

### ISSUE THREAD

**Issue by bhavyaagg** [internetarchive/wayback-machine-chrome#80]
Bootstrap 4 has been released in stable mode. So we can update this extension to use bootstrap 4 rather than bootstrap 3.

I would love to do this.

**Comment by strongSoda** [comment]
I would love to collaborate too.

**Comment by VishnuRaghavan** [comment]
Great, we can do it!

**Comment by anishsarangi** [comment]
Yes, We can do this. But instead of using Bootstrap, it will be good if we can use our own css .

**Comment by bamoha** [comment]
Hello, has this been completed? Why is this issue not closed yet?
