### ISSUE TITLE
Advanced feature #2 (radial tree) is buggy

### ISSUE THREAD

**Issue by rajvaibhavdubey** [internetarchive/wayback-machine-chrome#82]
Advanced feature #2 (radial tree) is buggy. On certain pages (example https://www.whitehouse.gov/) the modal on which the radial tree is displayed loses defined CSS properties. Its almost as if the CSS of the web page 'leaks' into the modal.
I'd like to work on this.

**Comment by vbanos** [comment]
Thank you for your comment, the Radial Tree has been improved significantly. The issue has been fixed.
