### ISSUE TITLE
Unclosed element 

### ISSUE THREAD

**Issue by Geekcoder555** [internetarchive/wayback-machine-chrome#98]
Error: Unclosed element t.length;a++)t[a][1].match(.

From line 1, column 994; to line 1, column 1506

=1;a<t.length;a++)t[a][1].match(/jpg|pdf|png|form|gif/)||(t[a][1]=t[a][1].trim().replace(":80/","/"),t[a][0]in…).join("/")),n=n.split("/").join("/"),i[e][t]=n}return i}(),l=o.map(function(e){if(e.length>1)return e[0]}

file to be updated:  radial-tree.umd.js

**Comment by sankalpdayal5** [comment]
Where is the file 'radial-tree.umd.js'?
Can you please specify the path for the given file
